### ISSUE TITLE
Server Crash with litematica

### ISSUE THREAD

**Issue by Shadowbee27** [Salandora/SophisticatedCore#2]
**Describe the bug**
When i tried viewing the material list of a farm in [litemetica](https://www.curseforge.com/minecraft/mc-mods/litematica) the server closed, because it crashed
`
[crash-2024-05-30_14.31.58-server.txt](https://github.com/Salandora/SophisticatedCore/files/15500128/crash-2024-05-30_14.31.58-server.txt)
`
to reproduce:

1. start the server
2. in game press m to open litematica main menu
3. click load schematic
4. choose one 
5. click material list
6. server crash

**Expected behavior**
server crash

**Comment by Shadowbee27** [comment]
I´ve been testing and the server even crashes when the mod is only installed on the client

**Comment by Salandora** [comment]
Ohh I know what is going on, as a quick fix add litematica to the server.
I accidentialy used a class from litematica without realizing it would be a problem....

**Comment by Salandora** [comment]
Correction don't add litematica, the class I used is in malilib, so adding malilib should be sufficient.
Sorry for the confusion

**Comment by Shadowbee27** [comment]
Hm the server still crashes, probably becaues malilib is only client side

**Comment by Salandora** [comment]
Wait what? Okay now I need to dig deeper into this, malilib should have solved that problem as the utility class I used is in there. 
Do you happen to have a new crash log?

**Comment by Shadowbee27** [comment]
[crash-2024-05-30_14.31.58-server.txt](https://github.com/Salandora/SophisticatedCore/files/15500128/crash-2024-05-30_14.31.58-server.txt) 
Yes

**Comment by Salandora** [comment]
That's the old one that you already posted in the report.

**Comment by Salandora** [comment]
Okay I additionally checked malilib real quick and yeah the fabric.mod.json is specifically set to client environments so the whole workaround would not work.

I should have a proper fix ready in a couple minutes, would you like to test it then?

**Comment by Shadowbee27** [comment]
[crash-2024-05-30_16.29.23-server.txt](https://github.com/Salandora/SophisticatedCore/files/15502672/crash-2024-05-30_16.29.23-server.txt)
This is the newest

**Comment by Shadowbee27** [comment]
![Screenshot 2024-05-30 180721](https://github.com/Salandora/SophisticatedCore/assets/169397554/f1c07d19-9a80-4e9d-8252-9725ffd48177)
Here are all mods form the server mod folder

**Comment by Shadowbee27** [comment]
Yes I can test it

**Comment by Salandora** [comment]
Okay github finished compiling now: 
https://github.com/Salandora/SophisticatedMods/actions/runs/9305793040

You wanna download the Artifacts file, it's a zip file.
In there you'll find a bunch of files you need these:

- sophisticatedcore-0.5.109+mc1.20.1-SNAPSHOT-build.81.jar
- sophisticatedbackpacks-3.19.5+mc1.20.1-SNAPSHOT-build.81.jar (If you have Backpacks)
- sophisticatedstorage-0.8.60+mc1.20.1-SNAPSHOT-build.81.jar (If you have Storage)

**Comment by Shadowbee27** [comment]
With the new version the porblem is fixed

**Comment by Salandora** [comment]
Bugfix release is out.
