### ISSUE TITLE
Random Crash whenever I opened a world and then waited/walked around to the load the world.

### ISSUE THREAD

**Issue by Irist-077** [Salandora/SophisticatedCore#23]
Random Crash whenever I opened a world and then waited/walked around to the load the world.
Same issue happens when I open my inventory.

[crash-2024-11-13_19.13.08-server.txt](https://github.com/user-attachments/files/17742578/crash-2024-11-13_19.13.08-server.txt))

![Screenshot 2024-11-13 202801](https://github.com/user-attachments/assets/c263bab7-31c5-435a-92cf-641ef7beb7f1)

![Screenshot 2024-11-13 203031](https://github.com/user-attachments/assets/ce0a64ba-e2a9-49b2-90b5-1b9d6eb83e63)

---------------------------------------------------
Minecraft-Version-1.21.1
fabric-loader-0.16.9-1.21.1
fabric-api-0.108.0+1.21.1

**Comment by Salandora** [comment]
Thanks for reporting, I'm aware of the issue it was reported in backpacks.
It's an incompatibility with porting-lib which is included in farmers delight. 
A fix is also in the dev branch and will be released soon.

**Comment by Irist-077** [comment]
Sounds like a plan. Thanks!

**Comment by Irist-077** [comment]
Actually, does sophisticated-backpacks have trinkets compatibility built-in? (So that it gets recognized as a trinket.)
Both of those mods worked naturally in 1.20.4, but not so in 1.21.1.

**Comment by Salandora** [comment]
Yeah it does but in trinket for 1.21.1 was a change I did not catch apparently now the folder "items" need to be called "item".
Fix is lined up just need to look into the litematica issue and then will release the fixes

**Comment by Irist-077** [comment]
Excellent! Thanks for all of the help!

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
