### ISSUE TITLE
Hopper linked to sophisticated storage barrel causes crash

### ISSUE THREAD

**Issue by Demadunk** [Salandora/SophisticatedCore#26]
Hopper set up to a sophisticated storage barrel has a crash on the hopper trying to insert the item.
I've only tested it with the diamond birch barrel, but the crash error indicates it may be everything that utilizes sophisticated core, including backpacks (haven't reproduced it with a bag as of this report)

https://mclo.gs/sj2blgY

To reproduce, go into a single player world. 
Hook up a hopper to a sophisticated storage barrel and throw an item into the hopper.
Any new attempts to rejoin the world will result in the same immediate crash due to the hopper trying again on first tick.

Minecraft 1.21.1, all three sophisticated storage mods up to date.

**Comment by Demadunk** [comment]
Confirmed crash happens with backpacks and chests trying to receive inserted items via hopper.

However, taking items out of these storages seem to be working just fine.

**Comment by Salandora** [comment]
Yeah I have a fix prepared got a report on backpacks for it and fixed it yesterday evening.

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
