### ISSUE TITLE
duplicating item when it eat from the Advanced feeding

### ISSUE THREAD

**Issue by x3Michels** [Salandora/SophisticatedCore#6]
**Describe the bug**
So with a few friends we found we can duplicate everything that was on the first slot of the left hand(this is a god thing) 
from the mod RPG INVENTORY/Slot Customization API
Hi mate, The problem is, can replace other weapons or tools in the inventory slots(really a bad thing)

**To Reproduce**
So The Problem is the "Advanced Feeding Upgrade" from the mod "Sophisticated Backpapcks" and the slot that you leave after changin to the main hand(item are in there.)

So everytime it eat for being hungry or when hurt, It will be replaced the blank slot or item for the one is on the main hand

**Expected behavior**
If we don't use it that upgrade wont duplicate or replace a item when it eat

**Screenshots**
![image](https://github.com/user-attachments/assets/8462e38f-4ff9-4a35-853c-8ab433edb137)
![image](https://github.com/user-attachments/assets/093b7c4a-8127-4902-b6d7-1f251a974728)

> **Versions**
> Fabric v1.20.1 modpack is the one I made for play with friends https://www.curseforge.com/minecraft/modpacks/otherwonderfulls
> On the github from RPV Inventory already made a issue and put a video there. https://github.com/TheRedBrain/rpg-inventory/issues/14

**Comment by Salandora** [comment]
Fixed in dev-feature-update

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
