### ISSUE TITLE
Block breaking particles not showing up with mod installed

### ISSUE THREAD

**Issue by LeahSupreme** [Salandora/SophisticatedCore#7]
**Describe the bug**
With this mod installed, when you break blocks, the block breaking particles fail to spawn (particularly noticeable with grass)

**To Reproduce**
Install mod (Tested on version 1.19.2), break blocks.

**Expected behavior**
Particles

**Versions**
sophisticatedcore-0.5.109+mc1.19.2-SNAPSHOT-build.103

**Comment by Salandora** [comment]
Can confirm this it's a bug in the current 1.19.2 version.
Fixed in fabric-dev-feature-update

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
